backend:
  name: github
  repo: nah-632/Bear-Phone
  branch: main
  # السطرين التاليين هما الحل لتجاوز الشاشة السوداء
  site_domain: nah-632.github.io
  display_url: https://nah-632.github.io/Bear-Phone/
  auth_type: implicit 

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "المنتجات"
    folder: "data/products"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "اسم المنتج", name: "title", widget: "string" }
      - { label: "السعر", name: "price", widget: "number" }
      - { label: "صورة المنتج", name: "image", widget: "image" }
