backend:
  name: github
  repo: nah-632/Bear-Phone
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "المنتجات"
    folder: "data/products"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "اسم المنتج", name: "title", widget: "string" }
      - { label: "السعر", name: "price", widget: "number" }
      - { label: "صورة المنتج", name: "image", widget: "image" }
